name: aplicacion2
description: App de gestión de tareas (Admin/Usuario)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  table_calendar: ^3.0.0
  image_picker: ^1.1.1
  http: ^1.2.0
  fl_chart: ^0.69.0   # ← AÑADIDO
  intl: ^0.19.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.0
  open_filex: ^4.4.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/icons/
    - assets/fonts/
    - assets/images/logo_light.png
    - assets/images/logo_dark.png

